### PR TITLE
min_valid_parantheses #issue_no:1

### PR DESCRIPTION
**Pull request by snehautekar05**
Hey @Saket6198 and @gdscpce,

I have added the code and algorithm for the minimum number of additions required to make a valid parentheses string. I have written the code in Java. Kindly check it and let me know if any changes are required.

### CODE REVIEW

**Comment by snehautekar05** [comment]
The above solution is optimized with a time complexity of O(n), where n is the length of the input string, and it uses O(1) extra space for the counters.

**Comment by Saket6198** [comment]
@snehautekar05 don't create another file for the algo, just write it and comment it out in the .java file.

**Comment by snehautekar05** [comment]
ok ...I will do the changes.

**Comment by snehautekar05** [comment]
I have made the changes ...Please check!

**Comment by Saket6198** [comment]
LGTM 👍

**Pull request merged**
