### PR TITLE
Solution for Deletion-String-Compare using python, issue: #14

### PR DESCRIPTION
**Pull request by negativenagesh**
@Saket6198 

# #14 

## Working:

1. Function Definition: The are_strings_identical(s, t) function checks if two strings, s and t, are the same after processing backspace operations represented by #.
2. Nested Function: Inside it, process_string(s) simulates how the text editor would process a string:
    * It uses a list (stack) to keep track of characters.
    * It iterates through each character:
         * If the character is #, it removes the last character from the stack if the stack is not empty.
         * If it's a regular character, it adds it to the stack.
    * Finally, it joins the characters in the stack to form the final processed string.
3. Comparison: The main function calls process_string for both input strings and returns True if the processed strings are identical, otherwise it returns False.

### CODE REVIEW

**Comment by negativenagesh** [comment]
> @Saket6198
> 
> # #14
> ### Solution for Deletion-String-Compare using python
> ## Working:
> 1. Function Definition: The are_strings_identical(s, t) function checks if two strings, s and t, are the same after processing backspace operations represented by #.
> 2. Nested Function: Inside it, process_string(s) simulates how the text editor would process a string:
>    
>    * It uses a list (stack) to keep track of characters.
>    * It iterates through each character:
>      
>      * If the character is #, it removes the last character from the stack if the stack is not empty.
>      * If it's a regular character, it adds it to the stack.
>    * Finally, it joins the characters in the stack to form the final processed string.
> 3. Comparison: The main function calls process_string for both input strings and returns True if the processed strings are identical, otherwise it returns False.

Working completely fine..

**Comment by Saket6198** [comment]
@negativenagesh Your solution is not space optimized, try to write the solution in O(1) SC. Also the write the working of the code/algo in the same .py file as comment (and try not to use GPT ;) its for your own good )

**Comment by negativenagesh** [comment]
@Saket6198 

Ok Sure I will take some time then..

**Comment by negativenagesh** [comment]
@Saket6198 

I have tried my best in modifying, please checkout, if you are not satisfied let me know

**Comment by Saket6198** [comment]
LGTM! 👍

**Pull request merged**
